#! /bin/sh

set -e

case "$1" in
    configure)
        # clean up eventually left over /usr/sbin/policy-rc.d, which
        # might not have been cleaned up correctly by 
        # fll-installer << 0.5.12.
        if [ -f /usr/sbin/policy-rc.d ] && \
           [ -z "$(dpkg-divert --list /usr/sbin/policy-rc.d)" ] && \
           [ "x$(md5sum -b /usr/sbin/policy-rc.d | awk '{print $1}')" = "x2f31905d39c6a4ed28a9217decbb7208" ]; then
            rm -f /usr/sbin/policy-rc.d
        fi

        if [ -r /etc/default/rcS ]; then
            . /etc/default/rcS
            if [ -n "$CONCURRENCY" ] && \
               [ ! "$CONCURRENCY" = "makefile" ] && \
               [ ! "$CONCURRENCY" = "none" ]; then
                sed -i "/^CONCURRENCY\=/d" /etc/default/rcS
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
